'use strict'

/**
 * z80 code hinting for codemirror 5.
 *
 * rob andrews <rob@aphlor.org>
 */

import CodeMirror from 'codemirror'

((codemirror) => {
  // block level so as not to pollute global space
  const z80_instructions = [
    'nop',
    'ld bc, ****',
    'ld (bc), a',
    'inc bc',
    'inc b',
    'dec b',
    'ld b, **',
    'rlca',
    'ex af, af\'',
    'add hl, bc',
    'ld a, (bc)',
    'dec bc',
    'inc c',
    'dec c',
    'ld c, **',
    'rrca',
    'djnz offset',
    'ld de, ****',
    'ld (de), a',
    'inc de',
    'inc d',
    'dec d',
    'ld d, **',
    'rla',
    'jr offset',
    'add hl, de',
    'ld a, (de)',
    'dec de',
    'inc e',
    'dec e',
    'ld e, **',
    'rra',
    'jr nz, offset',
    'ld hl, ****',
    'ld (****), hl',
    'inc hl',
    'inc h',
    'dec h',
    'ld h, **',
    'daa',
    'jr z, offset',
    'add hl, hl',
    'ld hl, (****)',
    'dec hl',
    'inc l',
    'dec l',
    'ld l, **',
    'cpl',
    'jr nc, offset',
    'ld sp, ****',
    'ld (****), a',
    'inc sp',
    'inc (hl)',
    'dec (hl)',
    'ld (hl), **',
    'scf',
    'jr c, offset',
    'add hl, sp',
    'ld a, (****)',
    'dec sp',
    'inc a',
    'dec a',
    'ld a, **',
    'ccf',
    'ld b, b',
    'ld b, c',
    'ld b, d',
    'ld b, e',
    'ld b, h',
    'ld b, l',
    'ld b, (hl)',
    'ld b, a',
    'ld c, b',
    'ld c, c',
    'ld c, d',
    'ld c, e',
    'ld c, h',
    'ld c, l',
    'ld c, (hl)',
    'ld c, a',
    'ld d, b',
    'ld d, c',
    'ld d, d',
    'ld d, e',
    'ld d, h',
    'ld d, l',
    'ld d, (hl)',
    'ld d, a',
    'ld e, b',
    'ld e, c',
    'ld e, d',
    'ld e, e',
    'ld e, h',
    'ld e, l',
    'ld e, (hl)',
    'ld e, a',
    'ld h, b',
    'ld h, c',
    'ld h, d',
    'ld h, e',
    'ld h, h',
    'ld h, l',
    'ld h, (hl)',
    'ld h, a',
    'ld l, b',
    'ld l, c',
    'ld l, d',
    'ld l, e',
    'ld l, h',
    'ld l, l',
    'ld l, (hl)',
    'ld l, a',
    'ld (hl), b',
    'ld (hl), c',
    'ld (hl), d',
    'ld (hl), e',
    'ld (hl), h',
    'ld (hl), l',
    'halt',
    'ld (hl), a',
    'ld a, b',
    'ld a, c',
    'ld a, d',
    'ld a, e',
    'ld a, h',
    'ld a, l',
    'ld a, (hl)',
    'ld a, a',
    'add a, b',
    'add a, c',
    'add a, d',
    'add a, e',
    'add a, h',
    'add a, l',
    'add a, (hl)',
    'add a, a',
    'adc a, b',
    'adc a, c',
    'adc a, d',
    'adc a, e',
    'adc a, h',
    'adc a, l',
    'adc a, (hl)',
    'adc a, a',
    'sub a, b',
    'sub a, c',
    'sub a, d',
    'sub a, e',
    'sub a, h',
    'sub a, l',
    'sub a, (hl)',
    'sub a, a',
    'sbc a, b',
    'sbc a, c',
    'sbc a, d',
    'sbc a, e',
    'sbc a, h',
    'sbc a, l',
    'sbc a, (hl)',
    'sbc a, a',
    'and a, b',
    'and a, c',
    'and a, d',
    'and a, e',
    'and a, h',
    'and a, l',
    'and a, (hl)',
    'and a, a',
    'xor a, b',
    'xor a, c',
    'xor a, d',
    'xor a, e',
    'xor a, h',
    'xor a, l',
    'xor a, (hl)',
    'xor a, a',
    'or a, b',
    'or a, c',
    'or a, d',
    'or a, e',
    'or a, h',
    'or a, l',
    'or a, (hl)',
    'or a, a',
    'cp b',
    'cp c',
    'cp d',
    'cp e',
    'cp h',
    'cp l',
    'cp (hl)',
    'cp a',
    'ret nz',
    'pop bc',
    'jp nz, ****',
    'jp ****',
    'call nz, ****',
    'push bc',
    'add a, **',
    'rst 00',
    'ret z',
    'ret',
    'jp z, ****',
    'call z, ****',
    'call ****',
    'adc a, **',
    'rst 8',
    'ret nc',
    'pop de',
    'jp nc, ****',
    'out (**), a',
    'call nc, ****',
    'push de',
    'sub **',
    'rst 10',
    'ret c',
    'exx',
    'jp c, ****',
    'in a, (**)',
    'call c, ****',
    'sbc a, **',
    'rst 18',
    'ret po',
    'pop hl',
    'jp po, ****',
    'ex (sp), hl',
    'call po, ****',
    'push hl',
    'and **',
    'rst 20',
    'ret pe',
    'jp hl',
    'jp pe, ****',
    'ex de, hl',
    'call pe, ****',
    'xor a, **',
    'rst 28',
    'ret p',
    'pop af',
    'jp p, ****',
    'di',
    'call p, ****',
    'push af',
    'or **',
    'rst 30',
    'ret m',
    'ld sp, hl',
    'jp m, ****',
    'ei',
    'call m, ****',
    'cp **',
    'rst 38',
    'rlc b',
    'rlc c',
    'rlc d',
    'rlc e',
    'rlc h',
    'rlc l',
    'rlc (hl)',
    'rlc a',
    'rrc b',
    'rrc c',
    'rrc d',
    'rrc e',
    'rrc h',
    'rrc l',
    'rrc (hl)',
    'rrc a',
    'rl b',
    'rl c',
    'rl d',
    'rl e',
    'rl h',
    'rl l',
    'rl (hl)',
    'rl a',
    'rr b',
    'rr c',
    'rr d',
    'rr e',
    'rr h',
    'rr l',
    'rr (hl)',
    'rr a',
    'sla b',
    'sla c',
    'sla d',
    'sla e',
    'sla h',
    'sla l',
    'sla (hl)',
    'sla a',
    'sra b',
    'sra c',
    'sra d',
    'sra e',
    'sra h',
    'sra l',
    'sra (hl)',
    'sra a',
    'sll b',
    'sll c',
    'sll d',
    'sll e',
    'sll h',
    'sll l',
    'sll (hl)',
    'sll a',
    'srl b',
    'srl c',
    'srl d',
    'srl e',
    'srl h',
    'srl l',
    'srl (hl)',
    'srl a',
    'bit 0, b',
    'bit 0, c',
    'bit 0, d',
    'bit 0, e',
    'bit 0, h',
    'bit 0, l',
    'bit 0, (hl)',
    'bit 0, a',
    'bit 1, b',
    'bit 1, c',
    'bit 1, d',
    'bit 1, e',
    'bit 1, h',
    'bit 1, l',
    'bit 1, (hl)',
    'bit 1, a',
    'bit 2, b',
    'bit 2, c',
    'bit 2, d',
    'bit 2, e',
    'bit 2, h',
    'bit 2, l',
    'bit 2, (hl)',
    'bit 2, a',
    'bit 3, b',
    'bit 3, c',
    'bit 3, d',
    'bit 3, e',
    'bit 3, h',
    'bit 3, l',
    'bit 3, (hl)',
    'bit 3, a',
    'bit 4, b',
    'bit 4, c',
    'bit 4, d',
    'bit 4, e',
    'bit 4, h',
    'bit 4, l',
    'bit 4, (hl)',
    'bit 4, a',
    'bit 5, b',
    'bit 5, c',
    'bit 5, d',
    'bit 5, e',
    'bit 5, h',
    'bit 5, l',
    'bit 5, (hl)',
    'bit 5, a',
    'bit 6, b',
    'bit 6, c',
    'bit 6, d',
    'bit 6, e',
    'bit 6, h',
    'bit 6, l',
    'bit 6, (hl)',
    'bit 6, a',
    'bit 7, b',
    'bit 7, c',
    'bit 7, d',
    'bit 7, e',
    'bit 7, h',
    'bit 7, l',
    'bit 7, (hl)',
    'bit 7, a',
    'res 0, b',
    'res 0, c',
    'res 0, d',
    'res 0, e',
    'res 0, h',
    'res 0, l',
    'res 0, (hl)',
    'res 0, a',
    'res 1, b',
    'res 1, c',
    'res 1, d',
    'res 1, e',
    'res 1, h',
    'res 1, l',
    'res 1, (hl)',
    'res 1, a',
    'res 2, b',
    'res 2, c',
    'res 2, d',
    'res 2, e',
    'res 2, h',
    'res 2, l',
    'res 2, (hl)',
    'res 2, a',
    'res 3, b',
    'res 3, c',
    'res 3, d',
    'res 3, e',
    'res 3, h',
    'res 3, l',
    'res 3, (hl)',
    'res 3, a',
    'res 4, b',
    'res 4, c',
    'res 4, d',
    'res 4, e',
    'res 4, h',
    'res 4, l',
    'res 4, (hl)',
    'res 4, a',
    'res 5, b',
    'res 5, c',
    'res 5, d',
    'res 5, e',
    'res 5, h',
    'res 5, l',
    'res 5, (hl)',
    'res 5, a',
    'res 6, b',
    'res 6, c',
    'res 6, d',
    'res 6, e',
    'res 6, h',
    'res 6, l',
    'res 6, (hl)',
    'res 6, a',
    'res 7, b',
    'res 7, c',
    'res 7, d',
    'res 7, e',
    'res 7, h',
    'res 7, l',
    'res 7, (hl)',
    'res 7, a',
    'set 0, b',
    'set 0, c',
    'set 0, d',
    'set 0, e',
    'set 0, h',
    'set 0, l',
    'set 0, (hl)',
    'set 0, a',
    'set 1, b',
    'set 1, c',
    'set 1, d',
    'set 1, e',
    'set 1, h',
    'set 1, l',
    'set 1, (hl)',
    'set 1, a',
    'set 2, b',
    'set 2, c',
    'set 2, d',
    'set 2, e',
    'set 2, h',
    'set 2, l',
    'set 2, (hl)',
    'set 2, a',
    'set 3, b',
    'set 3, c',
    'set 3, d',
    'set 3, e',
    'set 3, h',
    'set 3, l',
    'set 3, (hl)',
    'set 3, a',
    'set 4, b',
    'set 4, c',
    'set 4, d',
    'set 4, e',
    'set 4, h',
    'set 4, l',
    'set 4, (hl)',
    'set 4, a',
    'set 5, b',
    'set 5, c',
    'set 5, d',
    'set 5, e',
    'set 5, h',
    'set 5, l',
    'set 5, (hl)',
    'set 5, a',
    'set 6, b',
    'set 6, c',
    'set 6, d',
    'set 6, e',
    'set 6, h',
    'set 6, l',
    'set 6, (hl)',
    'set 6, a',
    'set 7, b',
    'set 7, c',
    'set 7, d',
    'set 7, e',
    'set 7, h',
    'set 7, l',
    'set 7, (hl)',
    'set 7, a',
    'rlc (ix+**), b',
    'rlc (ix+**), c',
    'rlc (ix+**), d',
    'rlc (ix+**), e',
    'rlc (ix+**), h',
    'rlc (ix+**), l',
    'rlc (ix+**)',
    'rlc (ix+**), a',
    'rrc (ix+**), b',
    'rrc (ix+**), c',
    'rrc (ix+**), d',
    'rrc (ix+**), e',
    'rrc (ix+**), h',
    'rrc (ix+**), l',
    'rrc (ix+**)',
    'rrc (ix+**), a',
    'rl (ix+**), b',
    'rl (ix+**), c',
    'rl (ix+**), d',
    'rl (ix+**), e',
    'rl (ix+**), h',
    'rl (ix+**), l',
    'rl (ix+**)',
    'rl (ix+**), a',
    'rr (ix+**), b',
    'rr (ix+**), c',
    'rr (ix+**), d',
    'rr (ix+**), e',
    'rr (ix+**), h',
    'rr (ix+**), l',
    'rr (ix+**)',
    'rr (ix+**), a',
    'sla (ix+**), b',
    'sla (ix+**), c',
    'sla (ix+**), d',
    'sla (ix+**), e',
    'sla (ix+**), h',
    'sla (ix+**), l',
    'sla (ix+**)',
    'sla (ix+**), a',
    'sra (ix+**), b',
    'sra (ix+**), c',
    'sra (ix+**), d',
    'sra (ix+**), e',
    'sra (ix+**), h',
    'sra (ix+**), l',
    'sra (ix+**)',
    'sra (ix+**), a',
    'sll (ix+**), b',
    'sll (ix+**), c',
    'sll (ix+**), d',
    'sll (ix+**), e',
    'sll (ix+**), h',
    'sll (ix+**), l',
    'sll (ix+**)',
    'sll (ix+**), a',
    'srl (ix+**), b',
    'srl (ix+**), c',
    'srl (ix+**), d',
    'srl (ix+**), e',
    'srl (ix+**), h',
    'srl (ix+**), l',
    'srl (ix+**)',
    'srl (ix+**), a',
    'bit 0, (ix+**)',
    'bit 1, (ix+**)',
    'bit 2, (ix+**)',
    'bit 3, (ix+**)',
    'bit 4, (ix+**)',
    'bit 5, (ix+**)',
    'bit 6, (ix+**)',
    'bit 7, (ix+**)',
    'res 0, (ix+**), b',
    'res 0, (ix+**), c',
    'res 0, (ix+**), d',
    'res 0, (ix+**), e',
    'res 0, (ix+**), h',
    'res 0, (ix+**), l',
    'res 0, (ix+**)',
    'res 0, (ix+**), a',
    'res 1, (ix+**), b',
    'res 1, (ix+**), c',
    'res 1, (ix+**), d',
    'res 1, (ix+**), e',
    'res 1, (ix+**), h',
    'res 1, (ix+**), l',
    'res 1, (ix+**)',
    'res 1, (ix+**), a',
    'res 2, (ix+**), b',
    'res 2, (ix+**), c',
    'res 2, (ix+**), d',
    'res 2, (ix+**), e',
    'res 2, (ix+**), h',
    'res 2, (ix+**), l',
    'res 2, (ix+**)',
    'res 2, (ix+**), a',
    'res 3, (ix+**), b',
    'res 3, (ix+**), c',
    'res 3, (ix+**), d',
    'res 3, (ix+**), e',
    'res 3, (ix+**), h',
    'res 3, (ix+**), l',
    'res 3, (ix+**)',
    'res 3, (ix+**), a',
    'res 4, (ix+**), b',
    'res 4, (ix+**), c',
    'res 4, (ix+**), d',
    'res 4, (ix+**), e',
    'res 4, (ix+**), h',
    'res 4, (ix+**), l',
    'res 4, (ix+**)',
    'res 4, (ix+**), a',
    'res 5, (ix+**), b',
    'res 5, (ix+**), c',
    'res 5, (ix+**), d',
    'res 5, (ix+**), e',
    'res 5, (ix+**), h',
    'res 5, (ix+**), l',
    'res 5, (ix+**)',
    'res 5, (ix+**), a',
    'res 6, (ix+**), b',
    'res 6, (ix+**), c',
    'res 6, (ix+**), d',
    'res 6, (ix+**), e',
    'res 6, (ix+**), h',
    'res 6, (ix+**), l',
    'res 6, (ix+**)',
    'res 6, (ix+**), a',
    'res 7, (ix+**), b',
    'res 7, (ix+**), c',
    'res 7, (ix+**), d',
    'res 7, (ix+**), e',
    'res 7, (ix+**), h',
    'res 7, (ix+**), l',
    'res 7, (ix+**)',
    'res 7, (ix+**), a',
    'set 0, (ix+**), b',
    'set 0, (ix+**), c',
    'set 0, (ix+**), d',
    'set 0, (ix+**), e',
    'set 0, (ix+**), h',
    'set 0, (ix+**), l',
    'set 0, (ix+**)',
    'set 0, (ix+**), a',
    'set 1, (ix+**), b',
    'set 1, (ix+**), c',
    'set 1, (ix+**), d',
    'set 1, (ix+**), e',
    'set 1, (ix+**), h',
    'set 1, (ix+**), l',
    'set 1, (ix+**)',
    'set 1, (ix+**), a',
    'set 2, (ix+**), b',
    'set 2, (ix+**), c',
    'set 2, (ix+**), d',
    'set 2, (ix+**), e',
    'set 2, (ix+**), h',
    'set 2, (ix+**), l',
    'set 2, (ix+**)',
    'set 2, (ix+**), a',
    'set 3, (ix+**), b',
    'set 3, (ix+**), c',
    'set 3, (ix+**), d',
    'set 3, (ix+**), e',
    'set 3, (ix+**), h',
    'set 3, (ix+**), l',
    'set 3, (ix+**)',
    'set 3, (ix+**), a',
    'set 4, (ix+**), b',
    'set 4, (ix+**), c',
    'set 4, (ix+**), d',
    'set 4, (ix+**), e',
    'set 4, (ix+**), h',
    'set 4, (ix+**), l',
    'set 4, (ix+**)',
    'set 4, (ix+**), a',
    'set 5, (ix+**), b',
    'set 5, (ix+**), c',
    'set 5, (ix+**), d',
    'set 5, (ix+**), e',
    'set 5, (ix+**), h',
    'set 5, (ix+**), l',
    'set 5, (ix+**)',
    'set 5, (ix+**), a',
    'set 6, (ix+**), b',
    'set 6, (ix+**), c',
    'set 6, (ix+**), d',
    'set 6, (ix+**), e',
    'set 6, (ix+**), h',
    'set 6, (ix+**), l',
    'set 6, (ix+**)',
    'set 6, (ix+**), a',
    'set 7, (ix+**), b',
    'set 7, (ix+**), c',
    'set 7, (ix+**), d',
    'set 7, (ix+**), e',
    'set 7, (ix+**), h',
    'set 7, (ix+**), l',
    'set 7, (ix+**)',
    'set 7, (ix+**), a',
    'add ix, bc',
    'add ix, de',
    'ld ix, ****',
    'ld (****), ix',
    'inc ix',
    'inc ixh',
    'dec ixh',
    'ld ixh, **',
    'add ix, ix',
    'ld ix, (****)',
    'dec ix',
    'inc ixl',
    'dec ixl',
    'ld ixl, **',
    'inc (ix+**)',
    'dec (ix+**)',
    'ld (ix+**), **',
    'add ix, sp',
    'ld b, ixh',
    'ld b, ixl',
    'ld b, (ix+**)',
    'ld c, ixh',
    'ld c, ixl',
    'ld c, (ix+**)',
    'ld d, ixh',
    'ld d, ixl',
    'ld d, (ix+**)',
    'ld e, ixh',
    'ld e, ixl',
    'ld e, (ix+**)',
    'ld ixh, b',
    'ld ixh, c',
    'ld ixh, d',
    'ld ixh, e',
    'ld ixh, ixh',
    'ld ixh, ixl',
    'ld h, (ix+**)',
    'ld ixh, a',
    'ld ixl, b',
    'ld ixl, c',
    'ld ixl, d',
    'ld ixl, e',
    'ld ixl, ixh',
    'ld ixl, ixl',
    'ld l, (ix+**)',
    'ld ixl, a',
    'ld (ix+**), b',
    'ld (ix+**), c',
    'ld (ix+**), d',
    'ld (ix+**), e',
    'ld (ix+**), h',
    'ld (ix+**), l',
    'ld (ix+**), a',
    'ld a, ixh',
    'ld a, ixl',
    'ld a, (ix+**)',
    'add a, ixh',
    'add a, ixl',
    'add a, (ix+**)',
    'adc a, ixh',
    'adc a, ixl',
    'adc a, (ix+**)',
    'sub a, ixh',
    'sub a, ixl',
    'sub a, (ix+**)',
    'sbc a, ixh',
    'sbc a, ixl',
    'sbc a, (ix+**)',
    'and a, ixh',
    'and a, ixl',
    'and a, (ix+**)',
    'xor a, ixh',
    'xor a, ixl',
    'xor a, (ix+**)',
    'or a, ixh',
    'or a, ixl',
    'or a, (ix+**)',
    'cp a, ixh',
    'cp a, ixl',
    'cp a, (ix+**)',
    'pop ix',
    'ex (sp), ix',
    'push ix',
    'jp ix',
    'ld sp, ix',
    'rlc (iy+**), b',
    'rlc (iy+**), c',
    'rlc (iy+**), d',
    'rlc (iy+**), e',
    'rlc (iy+**), h',
    'rlc (iy+**), l',
    'rlc (iy+**)',
    'rlc (iy+**), a',
    'rrc (iy+**), b',
    'rrc (iy+**), c',
    'rrc (iy+**), d',
    'rrc (iy+**), e',
    'rrc (iy+**), h',
    'rrc (iy+**), l',
    'rrc (iy+**)',
    'rrc (iy+**), a',
    'rl (iy+**), b',
    'rl (iy+**), c',
    'rl (iy+**), d',
    'rl (iy+**), e',
    'rl (iy+**), h',
    'rl (iy+**), l',
    'rl (iy+**)',
    'rl (iy+**), a',
    'rr (iy+**), b',
    'rr (iy+**), c',
    'rr (iy+**), d',
    'rr (iy+**), e',
    'rr (iy+**), h',
    'rr (iy+**), l',
    'rr (iy+**)',
    'rr (iy+**), a',
    'sla (iy+**), b',
    'sla (iy+**), c',
    'sla (iy+**), d',
    'sla (iy+**), e',
    'sla (iy+**), h',
    'sla (iy+**), l',
    'sla (iy+**)',
    'sla (iy+**), a',
    'sra (iy+**), b',
    'sra (iy+**), c',
    'sra (iy+**), d',
    'sra (iy+**), e',
    'sra (iy+**), h',
    'sra (iy+**), l',
    'sra (iy+**)',
    'sra (iy+**), a',
    'sll (iy+**), b',
    'sll (iy+**), c',
    'sll (iy+**), d',
    'sll (iy+**), e',
    'sll (iy+**), h',
    'sll (iy+**), l',
    'sll (iy+**)',
    'sll (iy+**), a',
    'srl (iy+**), b',
    'srl (iy+**), c',
    'srl (iy+**), d',
    'srl (iy+**), e',
    'srl (iy+**), h',
    'srl (iy+**), l',
    'srl (iy+**)',
    'srl (iy+**), a',
    'bit 0, (iy+**)',
    'bit 1, (iy+**)',
    'bit 2, (iy+**)',
    'bit 3, (iy+**)',
    'bit 4, (iy+**)',
    'bit 5, (iy+**)',
    'bit 6, (iy+**)',
    'bit 7, (iy+**)',
    'res 0, (iy+**), b',
    'res 0, (iy+**), c',
    'res 0, (iy+**), d',
    'res 0, (iy+**), e',
    'res 0, (iy+**), h',
    'res 0, (iy+**), l',
    'res 0, (iy+**)',
    'res 0, (iy+**), a',
    'res 1, (iy+**), b',
    'res 1, (iy+**), c',
    'res 1, (iy+**), d',
    'res 1, (iy+**), e',
    'res 1, (iy+**), h',
    'res 1, (iy+**), l',
    'res 1, (iy+**)',
    'res 1, (iy+**), a',
    'res 2, (iy+**), b',
    'res 2, (iy+**), c',
    'res 2, (iy+**), d',
    'res 2, (iy+**), e',
    'res 2, (iy+**), h',
    'res 2, (iy+**), l',
    'res 2, (iy+**)',
    'res 2, (iy+**), a',
    'res 3, (iy+**), b',
    'res 3, (iy+**), c',
    'res 3, (iy+**), d',
    'res 3, (iy+**), e',
    'res 3, (iy+**), h',
    'res 3, (iy+**), l',
    'res 3, (iy+**)',
    'res 3, (iy+**), a',
    'res 4, (iy+**), b',
    'res 4, (iy+**), c',
    'res 4, (iy+**), d',
    'res 4, (iy+**), e',
    'res 4, (iy+**), h',
    'res 4, (iy+**), l',
    'res 4, (iy+**)',
    'res 4, (iy+**), a',
    'res 5, (iy+**), b',
    'res 5, (iy+**), c',
    'res 5, (iy+**), d',
    'res 5, (iy+**), e',
    'res 5, (iy+**), h',
    'res 5, (iy+**), l',
    'res 5, (iy+**)',
    'res 5, (iy+**), a',
    'res 6, (iy+**), b',
    'res 6, (iy+**), c',
    'res 6, (iy+**), d',
    'res 6, (iy+**), e',
    'res 6, (iy+**), h',
    'res 6, (iy+**), l',
    'res 6, (iy+**)',
    'res 6, (iy+**), a',
    'res 7, (iy+**), b',
    'res 7, (iy+**), c',
    'res 7, (iy+**), d',
    'res 7, (iy+**), e',
    'res 7, (iy+**), h',
    'res 7, (iy+**), l',
    'res 7, (iy+**)',
    'res 7, (iy+**), a',
    'set 0, (iy+**), b',
    'set 0, (iy+**), c',
    'set 0, (iy+**), d',
    'set 0, (iy+**), e',
    'set 0, (iy+**), h',
    'set 0, (iy+**), l',
    'set 0, (iy+**)',
    'set 0, (iy+**), a',
    'set 1, (iy+**), b',
    'set 1, (iy+**), c',
    'set 1, (iy+**), d',
    'set 1, (iy+**), e',
    'set 1, (iy+**), h',
    'set 1, (iy+**), l',
    'set 1, (iy+**)',
    'set 1, (iy+**), a',
    'set 2, (iy+**), b',
    'set 2, (iy+**), c',
    'set 2, (iy+**), d',
    'set 2, (iy+**), e',
    'set 2, (iy+**), h',
    'set 2, (iy+**), l',
    'set 2, (iy+**)',
    'set 2, (iy+**), a',
    'set 3, (iy+**), b',
    'set 3, (iy+**), c',
    'set 3, (iy+**), d',
    'set 3, (iy+**), e',
    'set 3, (iy+**), h',
    'set 3, (iy+**), l',
    'set 3, (iy+**)',
    'set 3, (iy+**), a',
    'set 4, (iy+**), b',
    'set 4, (iy+**), c',
    'set 4, (iy+**), d',
    'set 4, (iy+**), e',
    'set 4, (iy+**), h',
    'set 4, (iy+**), l',
    'set 4, (iy+**)',
    'set 4, (iy+**), a',
    'set 5, (iy+**), b',
    'set 5, (iy+**), c',
    'set 5, (iy+**), d',
    'set 5, (iy+**), e',
    'set 5, (iy+**), h',
    'set 5, (iy+**), l',
    'set 5, (iy+**)',
    'set 5, (iy+**), a',
    'set 6, (iy+**), b',
    'set 6, (iy+**), c',
    'set 6, (iy+**), d',
    'set 6, (iy+**), e',
    'set 6, (iy+**), h',
    'set 6, (iy+**), l',
    'set 6, (iy+**)',
    'set 6, (iy+**), a',
    'set 7, (iy+**), b',
    'set 7, (iy+**), c',
    'set 7, (iy+**), d',
    'set 7, (iy+**), e',
    'set 7, (iy+**), h',
    'set 7, (iy+**), l',
    'set 7, (iy+**)',
    'set 7, (iy+**), a',
    'add iy, bc',
    'add iy, de',
    'ld iy, ****',
    'ld (****), iy',
    'inc iy',
    'inc iyh',
    'dec iyh',
    'ld iyh, **',
    'add iy, iy',
    'ld iy, (****)',
    'dec iy',
    'inc iyl',
    'dec iyl',
    'ld iyl, **',
    'inc (iy+**)',
    'dec (iy+**)',
    'ld (iy+**), **',
    'add iy, sp',
    'ld b, iyh',
    'ld b, iyl',
    'ld b, (iy+**)',
    'ld c, iyh',
    'ld c, iyl',
    'ld c, (iy+**)',
    'ld d, iyh',
    'ld d, iyl',
    'ld d, (iy+**)',
    'ld e, iyh',
    'ld e, iyl',
    'ld e, (iy+**)',
    'ld iyh, b',
    'ld iyh, c',
    'ld iyh, d',
    'ld iyh, e',
    'ld iyh, iyh',
    'ld iyh, iyl',
    'ld h, (iy+**)',
    'ld iyh, a',
    'ld iyl, b',
    'ld iyl, c',
    'ld iyl, d',
    'ld iyl, e',
    'ld iyl, iyh',
    'ld iyl, iyl',
    'ld l, (iy+**)',
    'ld iyl, a',
    'ld (iy+**), b',
    'ld (iy+**), c',
    'ld (iy+**), d',
    'ld (iy+**), e',
    'ld (iy+**), h',
    'ld (iy+**), l',
    'ld (iy+**), a',
    'ld a, iyh',
    'ld a, iyl',
    'ld a, (iy+**)',
    'add a, iyh',
    'add a, iyl',
    'add a, (iy+**)',
    'adc a, iyh',
    'adc a, iyl',
    'adc a, (iy+**)',
    'sub a, iyh',
    'sub a, iyl',
    'sub a, (iy+**)',
    'sbc a, iyh',
    'sbc a, iyl',
    'sbc a, (iy+**)',
    'and a, iyh',
    'and a, iyl',
    'and a, (iy+**)',
    'xor a, iyh',
    'xor a, iyl',
    'xor a, (iy+**)',
    'or a, iyh',
    'or a, iyl',
    'or a, (iy+**)',
    'cp a, iyh',
    'cp a, iyl',
    'cp a, (iy+**)',
    'pop iy',
    'ex (sp), iy',
    'push iy',
    'jp iy',
    'ld sp, iy',
    'in b, (c)',
    'out (c), b',
    'sbc hl, bc',
    'ld (****), bc',
    'neg',
    'retn',
    'im 0',
    'ld i, a',
    'in c, (c)',
    'out (c), c',
    'adc hl, bc',
    'ld bc, (****)',
    'ld r, a',
    'in d, (c)',
    'out (c), d',
    'sbc hl, de',
    'ld (****), de',
    'im 1',
    'ld a, i',
    'in e, (c)',
    'out (c), e',
    'adc hl, de',
    'ld de, (****)',
    'im 2',
    'ld a, r',
    'in h, (c)',
    'out (c), h',
    'sbc hl, hl',
    'ld (****), hl',
    'rrd',
    'in l, (c)',
    'out (c), l',
    'adc hl, hl',
    'ld hl, (****)',
    'rld',
    'in f, (c)',
    'out (c), 0',
    'sbc hl, sp',
    'ld (****), sp',
    'in a, (c)',
    'out (c), a',
    'adc hl, sp',
    'ld sp, (****)',
    'ldi',
    'cpi',
    'ini',
    'outi',
    'ldd',
    'cpd',
    'ind',
    'outd',
    'ldir',
    'cpir',
    'inir',
    'otir',
    'lddr',
    'cpdr',
    'indr',
    'otdr'
  ]

  codemirror.registerHelper('hint', 'z80', (editor, options) => {
    let cursor = editor.getCursor(),
        token = editor.getTokenAt(cursor)

    // find any matches which start with token.string
    let matches = z80_instructions.filter((val) => {
      if (val.indexOf(token.string) === 0)
        return val
    })

    return {
      list: matches,
      from: codemirror.Pos(cursor.line, token.start),
      to: codemirror.Pos(cursor.line, token.end)
    }
  })
})(CodeMirror)
