# continuous integration setup file
# rob andrews <rob@aphlor.org>

language: node_js

node_js:
  - 15

cache: npm

before_script:
  - npm install

script:
  - npm run build:dev
  - npm run build
  - npm run test
